// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Product_Config_Customer_v0.Data;

#nullable disable

namespace Product_Config_Customer_v0.Migrations.DomainManagementDb
{
    [DbContext(typeof(DomainManagementDbContext))]
    [Migration("20251125101556_Add_DomainAdminUsers_Table")]
    partial class Add_DomainAdminUsers_Table
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Product_Config_Customer_v0.DomainManagement.Entity.AnonymousRequestControl", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AllowAnonymousRequest")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("DatabaseName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DomainName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("AnonymousRequestControls", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AllowAnonymousRequest = false,
                            DatabaseName = "CustDb_Jvl",
                            DateCreated = new DateTime(2025, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(2025, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DomainName = "Jvl"
                        },
                        new
                        {
                            Id = 2,
                            AllowAnonymousRequest = true,
                            DatabaseName = "CustDb_Motor",
                            DateCreated = new DateTime(2025, 11, 4, 7, 58, 12, 0, DateTimeKind.Unspecified),
                            DateModified = new DateTime(2025, 11, 17, 11, 26, 16, 0, DateTimeKind.Unspecified),
                            DomainName = "Motor"
                        });
                });

            modelBuilder.Entity("Product_Config_Customer_v0.Models.Entity.Domain_Admin_User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("varchar(150)");

                    b.Property<bool>("EmailVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PasswordResetExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PasswordResetOtp")
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("DomainAdminUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
